# Generated by Django 4.2.4 on 2023-08-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
