# Generated by Django 4.2.4 on 2024-07-10 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='incidents_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('malware', 'malware'), ('phishing', 'phishing'), ('others', 'others')], max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('Report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=200)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
