# Generated by Django 4.2.2 on 2023-08-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='report_incidents',
            new_name='incidents_detail',
        ),
    ]
