# Generated by Django 4.2.4 on 2023-08-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_rename_report_incidents_incidents_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents_detail',
            name='status',
            field=models.CharField(choices=[('malware', 'malware'), ('phishing', 'phishing'), ('others', 'others')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
