# Generated by Django 4.2.4 on 2023-08-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidents_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents_detail',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=200),
        ),
    ]
