# Generated by Django 4.2.4 on 2023-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incidents_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents_detail',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
